version: "3"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - type: bind
        source: ./timescaledb-data
        target: /var/lib/postgresql/data
  top_tweets:
    image: calderwhite/top-tweets
    restart: always
    ports:
      - "443:8080"
    hostname: toptweets.calderwhite.com
    environment:
      - TWITTER_BEARER
      - TOP_TWEETS_MODE=PRODUCTION
    volumes:
      - type: bind
        source: ./backups
        target: /app/backups
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
  db_sidecar:
    image: calderwhite/db-sidecar
    environment:
      - TOP_TWEETS_MODE=PRODUCTION