version: "3"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - type: bind
        source: ./timescaledb-data
        target: /var/lib/postgresql/data
  top_tweets:
    build: .
    image: calderwhite/top-tweets
    ports:
      - "80:8080"
    environment:
      - TWITTER_BEARER
    volumes:
      - type: bind
        source: ./backups
        target: /app/backups
  db_sidecar:
    build: 
      context: .
      dockerfile: dockerfiles/db_sidecar
    image: calderwhite/db-sidecar