version: "3"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    restart: always
    volumes:
      - type: bind
        source: ./timescaledb-data
        target: /var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "1000k"
        max-file: "5"
        compress: "true"
  top_tweets:
    image: calderwhite/top-tweets
    restart: always
    ports:
      - "443:8080"
    hostname: toptweets.calderwhite.com
    environment:
      - TWITTER_BEARER
      - TOP_TWEETS_MODE=PRODUCTION
      - GOOGLE_APPLICATION_CREDENTIALS=/app/creds/translate-creds.json
      - GIN_MODE=release
    volumes:
      - type: bind
        source: ./backups
        target: /app/backups
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
      - type: bind
        source: ./creds
        target: /app/creds
    tmpfs:
      - /app/tmp/build
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"
        compress: "true"
  db_sidecar:
    image: calderwhite/db-sidecar
    environment:
      - TOP_TWEETS_MODE=PRODUCTION
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"
        compress: "true"
